services:
  mongodb:
    image: mongo:8
    container_name: form-rsvp-mongodb
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - form-rsvp-mongodb-data:/data/db

volumes:
  form-rsvp-mongodb-data:
